# Generated by Django 5.2.4 on 2025-07-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="avatar",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Avatar"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Avatar"
            ),
        ),
    ]
