# Generated by Django 5.0 on 2025-07-02 18:45

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalListing",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price per night"
                    ),
                ),
                ("rooms", models.FloatField(verbose_name="Rooms")),
                (
                    "property_type",
                    models.CharField(max_length=50, verbose_name="Property type"),
                ),
                ("amenities", models.JSONField(default=list, verbose_name="Amenities")),
                ("photos", models.JSONField(default=list, verbose_name="Photos")),
                (
                    "availability",
                    models.JSONField(default=dict, verbose_name="Availability"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created at"
                    ),
                ),
                (
                    "popularity",
                    models.PositiveIntegerField(default=0, verbose_name="Popularity"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Listing",
                "verbose_name_plural": "historical Listings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "title_en",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "title_de",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_de",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_ru",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price per night"
                    ),
                ),
                ("rooms", models.FloatField(verbose_name="Rooms")),
                (
                    "property_type",
                    models.CharField(max_length=50, verbose_name="Property type"),
                ),
                ("amenities", models.JSONField(default=list, verbose_name="Amenities")),
                ("photos", models.JSONField(default=list, verbose_name="Photos")),
                (
                    "availability",
                    models.JSONField(default=dict, verbose_name="Availability"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "popularity",
                    models.PositiveIntegerField(default=0, verbose_name="Popularity"),
                ),
            ],
            options={
                "verbose_name": "Listing",
                "verbose_name_plural": "Listings",
            },
        ),
    ]
