# Generated by Django 5.0 on 2025-07-02 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallisting",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicallisting",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["is_active"], name="is_act_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["price_per_night"], name="price_night_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["created_at"], name="created_at__idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["title"], name="list_title_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["popularity"], name="popularity_idx"),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.UniqueConstraint(
                fields=("address", "user"), name="unique_address_user"
            ),
        ),
    ]
