# Generated by Django 5.0 on 2025-07-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallisting",
            name="description",
            field=models.TextField(default="", verbose_name="Description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicallisting",
            name="title",
            field=models.CharField(default="", max_length=255, verbose_name="Title"),
            preserve_default=False,
        ),
    ]
