# Generated by Django 5.0 on 2025-07-03 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_historicallisting_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallisting",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="historicallisting",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="historicallisting",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="historicallisting",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["city"], name="city_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["country"], name="country_idx"),
        ),
    ]
