# Generated by Django 5.0 on 2025-07-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_historicallisting_city_historicallisting_country_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicallisting",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Listing",
                "verbose_name_plural": "historical Listings (Объявления)",
            },
        ),
        migrations.AlterModelOptions(
            name="listing",
            options={
                "verbose_name": "Listing",
                "verbose_name_plural": "Listings (Объявления)",
            },
        ),
    ]
