# Generated by Django 5.0 on 2025-07-10 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_alter_historicallisting_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Amenity"
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
            },
        ),
        migrations.RemoveField(
            model_name="historicallisting",
            name="amenities",
        ),
        migrations.RemoveField(
            model_name="historicallisting",
            name="availability",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="availability",
        ),
        migrations.AlterField(
            model_name="historicallisting",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Apartment", "Apartment"),
                    ("House", "House"),
                    ("Studio", "Studio"),
                    ("Shared Room", "Shared Room"),
                    ("Villa", "Villa"),
                    ("ONE_ROOM", "1-комнатная квартира"),
                    ("TWO_ROOM", "2-комнатная квартира"),
                    ("THREE_ROOM", "3-комнатная квартира"),
                    ("FOUR_ROOM", "4-комнатная квартира"),
                    ("DORM", "Общежитие"),
                ],
                default="Apartment",
                max_length=50,
                verbose_name="Property type",
            ),
        ),
        migrations.RemoveField(
            model_name="listing",
            name="amenities",
        ),
        migrations.AlterField(
            model_name="listing",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Apartment", "Apartment"),
                    ("House", "House"),
                    ("Studio", "Studio"),
                    ("Shared Room", "Shared Room"),
                    ("Villa", "Villa"),
                    ("ONE_ROOM", "1-комнатная квартира"),
                    ("TWO_ROOM", "2-комнатная квартира"),
                    ("THREE_ROOM", "3-комнатная квартира"),
                    ("FOUR_ROOM", "4-комнатная квартира"),
                    ("DORM", "Общежитие"),
                ],
                default="Apartment",
                max_length=50,
                verbose_name="Property type",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, to="listings.amenity", verbose_name="Amenities"
            ),
        ),
        migrations.CreateModel(
            name="AvailabilitySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Is Available"),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="listings.listing",
                        verbose_name="Listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Availability Slot",
                "verbose_name_plural": "Availability Slots",
                "indexes": [
                    models.Index(
                        fields=["listing", "date"],
                        name="listings_av_listing_3e9e3a_idx",
                    ),
                    models.Index(fields=["date"], name="listings_av_date_b89907_idx"),
                ],
                "unique_together": {("listing", "date")},
            },
        ),
    ]
