# Generated by Django 5.0 on 2025-07-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_amenity_remove_historicallisting_amenities_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallisting",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Apartment", "Apartment"),
                    ("House", "House"),
                    ("Studio", "Studio"),
                    ("Shared Room", "Shared Room"),
                    ("Villa", "Villa"),
                    ("ONE_ROOM", "One-Room Apartment"),
                    ("TWO_ROOM", "Two-Room Apartment"),
                    ("THREE_ROOM", "Three-Room Apartment"),
                    ("FOUR_ROOM", "Four-Room Apartment"),
                    ("Dormitory", "Dormitory"),
                    ("Penthouse", "Penthouse"),
                    ("Townhouse", "Townhouse"),
                    ("Cottage", "Cottage"),
                    ("Condominium", "Condominium"),
                    ("Loft", "Loft"),
                    ("Duplex", "Duplex"),
                    ("Bungalow", "Bungalow"),
                ],
                default="Apartment",
                max_length=50,
                verbose_name="Property type",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Apartment", "Apartment"),
                    ("House", "House"),
                    ("Studio", "Studio"),
                    ("Shared Room", "Shared Room"),
                    ("Villa", "Villa"),
                    ("ONE_ROOM", "One-Room Apartment"),
                    ("TWO_ROOM", "Two-Room Apartment"),
                    ("THREE_ROOM", "Three-Room Apartment"),
                    ("FOUR_ROOM", "Four-Room Apartment"),
                    ("Dormitory", "Dormitory"),
                    ("Penthouse", "Penthouse"),
                    ("Townhouse", "Townhouse"),
                    ("Cottage", "Cottage"),
                    ("Condominium", "Condominium"),
                    ("Loft", "Loft"),
                    ("Duplex", "Duplex"),
                    ("Bungalow", "Bungalow"),
                ],
                default="Apartment",
                max_length=50,
                verbose_name="Property type",
            ),
        ),
    ]
