# Generated by Django 5.0 on 2025-07-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_alter_historicallisting_property_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities (Удобства)",
            },
        ),
        migrations.AlterModelOptions(
            name="availabilityslot",
            options={
                "verbose_name": "Availability Slot",
                "verbose_name_plural": "Availability Slots (Интервалы доступности)",
            },
        ),
    ]
