# Generated by Django 5.2.4 on 2025-07-28 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_alter_amenity_options_alter_availabilityslot_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallisting",
            name="main_photo",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Main photo"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="main_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="listings/main/%Y/%m/",
                verbose_name="Main photo",
            ),
        ),
        migrations.AlterField(
            model_name="historicallisting",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Apartment", "Apartment"),
                    ("House", "House"),
                    ("Studio", "Studio"),
                    ("Villa", "Villa"),
                    ("ONE_ROOM", "One-Room Apartment"),
                    ("TWO_ROOM", "Two-Room Apartment"),
                    ("THREE_ROOM", "Three-Room Apartment"),
                    ("FOUR_ROOM", "Four-Room Apartment"),
                    ("Penthouse", "Penthouse"),
                    ("Loft", "Loft"),
                ],
                default="Apartment",
                max_length=50,
                verbose_name="Property type",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Apartment", "Apartment"),
                    ("House", "House"),
                    ("Studio", "Studio"),
                    ("Villa", "Villa"),
                    ("ONE_ROOM", "One-Room Apartment"),
                    ("TWO_ROOM", "Two-Room Apartment"),
                    ("THREE_ROOM", "Three-Room Apartment"),
                    ("FOUR_ROOM", "Four-Room Apartment"),
                    ("Penthouse", "Penthouse"),
                    ("Loft", "Loft"),
                ],
                default="Apartment",
                max_length=50,
                verbose_name="Property type",
            ),
        ),
        migrations.CreateModel(
            name="ListingPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="listings/photos/%Y/%m/")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing Photo",
                "verbose_name_plural": "Listing Photos",
                "ordering": ("order",),
            },
        ),
    ]
