# Generated by Django 5.2.4 on 2025-07-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_historicallisting_main_photo_listing_main_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallisting",
            name="photos",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="photos",
        ),
    ]
