# Generated by Django 5.2.4 on 2025-07-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0010_remove_historicallisting_photos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallisting",
            name="main_photo",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="main_photo",
        ),
    ]
