# Generated by Django 5.2.4 on 2025-07-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0011_remove_historicallisting_main_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallisting",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="historicallisting",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="longitude",
        ),
    ]
