# Generated by Django 5.0 on 2025-07-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalreview",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Review",
                "verbose_name_plural": "historical Reviews (Отзывы)",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews (Отзывы)",
            },
        ),
        migrations.AddField(
            model_name="historicalreview",
            name="landlord_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="landlord_response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
