# Generated by Django 5.0 on 2025-07-02 18:45

import django.contrib.gis.db.models.fields
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalLocation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Coordinates"
                    ),
                ),
                (
                    "federal_state",
                    models.CharField(
                        choices=[
                            ("Bayern", "Bayern"),
                            ("Berlin", "Berlin"),
                            ("Hamburg", "Hamburg"),
                            ("Nordrhein-Westfalen", "Nordrhein-Westfalen"),
                            ("Baden-Württemberg", "Baden-Württemberg"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Munich", "Munich"),
                            ("Berlin", "Berlin"),
                            ("Hamburg", "Hamburg"),
                            ("Düsseldorf", "Düsseldorf"),
                            ("Stuttgart", "Stuttgart"),
                            ("Cologne", "Cologne"),
                            ("Frankfurt", "Frankfurt"),
                            ("Leipzig", "Leipzig"),
                        ],
                        max_length=100,
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Location",
                "verbose_name_plural": "historical Locations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Coordinates"
                    ),
                ),
                (
                    "federal_state",
                    models.CharField(
                        choices=[
                            ("Bayern", "Bayern"),
                            ("Berlin", "Berlin"),
                            ("Hamburg", "Hamburg"),
                            ("Nordrhein-Westfalen", "Nordrhein-Westfalen"),
                            ("Baden-Württemberg", "Baden-Württemberg"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "federal_state_en",
                    models.CharField(
                        choices=[
                            ("Bayern", "Bayern"),
                            ("Berlin", "Berlin"),
                            ("Hamburg", "Hamburg"),
                            ("Nordrhein-Westfalen", "Nordrhein-Westfalen"),
                            ("Baden-Württemberg", "Baden-Württemberg"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "federal_state_de",
                    models.CharField(
                        choices=[
                            ("Bayern", "Bayern"),
                            ("Berlin", "Berlin"),
                            ("Hamburg", "Hamburg"),
                            ("Nordrhein-Westfalen", "Nordrhein-Westfalen"),
                            ("Baden-Württemberg", "Baden-Württemberg"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "federal_state_ru",
                    models.CharField(
                        choices=[
                            ("Bayern", "Bayern"),
                            ("Berlin", "Berlin"),
                            ("Hamburg", "Hamburg"),
                            ("Nordrhein-Westfalen", "Nordrhein-Westfalen"),
                            ("Baden-Württemberg", "Baden-Württemberg"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Munich", "Munich"),
                            ("Berlin", "Berlin"),
                            ("Hamburg", "Hamburg"),
                            ("Düsseldorf", "Düsseldorf"),
                            ("Stuttgart", "Stuttgart"),
                            ("Cologne", "Cologne"),
                            ("Frankfurt", "Frankfurt"),
                            ("Leipzig", "Leipzig"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "city_en",
                    models.CharField(
                        choices=[
                            ("Munich", "Munich"),
                            ("Berlin", "Berlin"),
                            ("Hamburg", "Hamburg"),
                            ("Düsseldorf", "Düsseldorf"),
                            ("Stuttgart", "Stuttgart"),
                            ("Cologne", "Cologne"),
                            ("Frankfurt", "Frankfurt"),
                            ("Leipzig", "Leipzig"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "city_de",
                    models.CharField(
                        choices=[
                            ("Munich", "Munich"),
                            ("Berlin", "Berlin"),
                            ("Hamburg", "Hamburg"),
                            ("Düsseldorf", "Düsseldorf"),
                            ("Stuttgart", "Stuttgart"),
                            ("Cologne", "Cologne"),
                            ("Frankfurt", "Frankfurt"),
                            ("Leipzig", "Leipzig"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "city_ru",
                    models.CharField(
                        choices=[
                            ("Munich", "Munich"),
                            ("Berlin", "Berlin"),
                            ("Hamburg", "Hamburg"),
                            ("Düsseldorf", "Düsseldorf"),
                            ("Stuttgart", "Stuttgart"),
                            ("Cologne", "Cologne"),
                            ("Frankfurt", "Frankfurt"),
                            ("Leipzig", "Leipzig"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("street", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
    ]
