# Generated by Django 5.0 on 2025-07-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicallocation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Location",
                "verbose_name_plural": "historical Locations (Локация)",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations (Локация)",
            },
        ),
    ]
