# Generated by Django 5.2.4 on 2025-07-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0012_remove_historicallisting_latitude_and_more"),
        ("locations", "0004_alter_historicallocation_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="listing",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="listings.listing",
            ),
        ),
    ]
