# Generated by Django 5.0 on 2025-07-02 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_initial"),
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="listings.listing",
                verbose_name="Listing",
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="status_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["start_date"], name="start_date_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["end_date"], name="end_date_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["listing", "status"], name="listing_status_idx"),
        ),
    ]
