# Generated by Django 5.0 on 2025-07-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings (Бронирование)",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbooking",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Booking",
                "verbose_name_plural": "historical Bookings (Бронирование)",
            },
        ),
    ]
