### `.github/workflows/ci.yml`

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: miet_system
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      redis:
        image: redis:7.0
        ports:
          - 6379:6379
      rabbitmq:
        image: rabbitmq:3.13
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        env:
          DB_NAME: miet_system
          DB_USER: user
          DB_PASSWORD: password
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          REDIS_URL: redis://127.0.0.1:6379/0
          CELERY_BROKER_URL: amqp://guest:guest@127.0.0.1:5672//
        run: python manage.py migrate
      - name: Run tests
        env:
          DB_NAME: miet_system
          DB_USER: user
          DB_PASSWORD: password
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          REDIS_URL: redis://127.0.0.1:6379/0
          CELERY_BROKER_URL: amqp://guest:guest@127.0.0.1:5672//
        run: pytest --cov=. --cov-report=xml
      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
